# Generated by Django 5.1.3 on 2024-11-17 13:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('year_founded', models.CharField(blank=True, max_length=4, null=True, validators=[app.models.validate_year])),
                ('industry', models.CharField(max_length=255)),
                ('size_range', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=200)),
                ('linkedin_url', models.URLField()),
                ('current_employee_estimate', models.IntegerField()),
                ('total_employee_estimate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
